module.exports = {
  docs: [
    'introduction',
    {
      type: 'doc',
      id: 'lido-v3-whitepaper',
      className: 'sidebar-v3-highlight',
    },
    'lido-dao',
    'lips',
    'guides/lido-tokens-integration-guide',
    'prd',
    {
      type: 'category',
      label: 'Guides',
      items: [
        {
          type: 'category',
          label: 'Curated Module',
          items: [
            'guides/curated-module/general-overview',
            'guides/curated-module/validator-keys',
            'guides/curated-module/el-rewards-configuration',
            {
              type: 'category',
              label: 'Validator Exits Automation',
              items: [
                'guides/curated-module/exits/introduction',
                'guides/curated-module/exits/general-information',
                'guides/curated-module/exits/exit-message-generation-signing',
                'guides/curated-module/exits/flow-examples',
                'guides/curated-module/exits/tooling-setup',
              ],
            },
          ],
        },
        'guides/oracle-operator-manual',
        {
          type: 'category',
          label: 'Oracle specification',
          items: [
            'guides/oracle-spec/accounting-oracle',
            'guides/oracle-spec/validator-exit-bus',
            'guides/oracle-spec/penalties',
          ],
        },
        'guides/deposit-security-manual',
        {
          type: 'category',
          label: 'Governance and Voting',
          items: [
            'guides/etherscan-voting',
            'guides/dg-guide',
            'guides/easy-track-guide',
          ],
        },
        {
          type: 'category',
          label: 'Multisig Operations',
          items: [
            'guides/address-ownership-guide',
            'guides/multisig-signer-manual',
            'guides/multisig-shadow-owners',
            'guides/checking-gnosis-safe',
          ],
        },
        {
          type: 'category',
          label: 'Tooling',
          items: [
            'guides/tooling',
            'guides/validator-ejector-guide',
            'guides/kapi-guide',
            'guides/reward-distributor-bot',
            'guides/depositor-bot',
            'guides/late-prover-bot',
            'guides/validator-exit-bot',
          ],
        },
        'guides/protocol-levers',
        'guides/1inch-pool-rewards',
        'guides/early-staker-airdrop',
        'guides/jumpgates',
        'guides/verify-steth-on-optimism-upgrade-manual',
        {
          type: 'category',
          label: 'Archived',
          items: [
            'guides/multisig-deployment',
            'guides/checking-aragon-vote',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Integrations',
      items: [
        'integrations/api',
        'integrations/wallets',
        'integrations/sdk',
        'integrations/subgraph',
      ],
    },
    {
      type: 'category',
      label: 'Token guides',
      items: [
        'token-guides/steth-superuser-functions',
        'token-guides/cross-chain-tokens-guide',
      ],
    },
    {
      type: 'category',
      label: 'Contracts',
      items: [
        'contracts/lido-locator',
        'contracts/lido',
        'contracts/accounting',
        'contracts/eip712-steth',
        'contracts/accounting-oracle',
        'contracts/validators-exit-bus-oracle',
        'contracts/hash-consensus',
        'contracts/oracle-report-sanity-checker',
        'contracts/oracle-daemon-config',
        'contracts/staking-router',
        'contracts/vault-hub',
        'contracts/staking-vault',
        'contracts/predeposit-guarantee',
        'contracts/operator-grid',
        'contracts/lazy-oracle',
        'contracts/staking-vault-factory',
        'contracts/staking-vault-beacon',
        'contracts/dashboard',
        'contracts/validator-consolidation-requests',
        'contracts/node-operators-registry',
        'contracts/withdrawal-queue-erc721',
        'contracts/withdrawal-vault',
        'contracts/wsteth',
        'contracts/wsteth-staker',
        'contracts/deposit-security-module',
        'contracts/data-bus',
        'contracts/burner',
        'contracts/lido-execution-layer-rewards-vault',
        'contracts/mev-boost-relays-allowed-list',
        'contracts/trp-vesting-escrow',
        'contracts/circuit-breaker',
        'contracts/reserve',
        'contracts/ossifiable-proxy',
        'contracts/consolidation-bus',
        'contracts/consolidation-gateway',
        'contracts/consolidation-migrator',
        'contracts/top-up-gateway',
      ],
    },
    {
      type: 'category',
      label: 'Security',
      items: [
        'security/bugbounty',
        'security/audits',
        'security/safeharbor',
        'security/disclosures',
      ],
    },
    {
      type: 'category',
      label: 'Deployed contracts',
      link: { type: 'doc', id: 'deployed-contracts/index' },
      items: [
        { type: 'doc', id: 'deployed-contracts/index', label: 'Mainnet' },
        'deployed-contracts/hoodi',
      ],
    },
    {
      type: 'category',
      label: 'Multisigs',
      items: [
        'multisigs/emergency-brakes',
        'multisigs/committees',
        'multisigs/alliance',
        'multisigs/other',
      ],
    },
    {
      type: 'category',
      label: 'Holders',
      items: [
        'holders/lido-oracle',
        'holders/lido-council-daemon',
      ],
    },
    {
      type: 'category',
      label: 'IPFS',
      items: [
        'ipfs/about',
        'ipfs/release-flow',
        'ipfs/security',
        'ipfs/hash-verification',
        'ipfs/apps-list'
      ],
    },
    {
      type: 'category',
      label: 'Staking Modules',
      link: { type: 'doc', id: 'staking-modules/index' },
      items: [
        'staking-modules/node-operators',
        'staking-modules/rewards',
        'staking-modules/validator-exits',
        { type: 'doc', id: 'staking-modules/permissions', label: 'Permissions' },
        'staking-modules/further-reading',
        {
          type: 'category',
          label: 'Contracts',
          link: { type: 'doc', id: 'staking-modules/contracts/index' },
          items: [
            {
              type: 'category',
              label: 'Module',
              collapsed: false,
              items: [
              { type: 'doc', id: 'staking-modules/contracts/CuratedModule', label: 'CuratedModule (CMv2)' },
              { type: 'doc', id: 'staking-modules/contracts/CSModule', label: 'CSModule (CSM)' },
              ],
            },
            {
              type: 'category',
              label: 'Entry gates',
              collapsed: false,
              items: [
              { type: 'doc', id: 'staking-modules/contracts/CuratedGate', label: 'CuratedGate (CMv2)' },
              { type: 'doc', id: 'staking-modules/contracts/PermissionlessGate', label: 'PermissionlessGate (CSM)' },
              { type: 'doc', id: 'staking-modules/contracts/VettedGate', label: 'VettedGate (CSM)' },
              { type: 'doc', id: 'staking-modules/contracts/MerkleGateFactory', label: 'MerkleGateFactory' },
              ],
            },
            {
              type: 'category',
              label: 'Bond and rewards',
              collapsed: false,
              items: [
              { type: 'doc', id: 'staking-modules/contracts/Accounting', label: 'Accounting' },
              { type: 'doc', id: 'staking-modules/contracts/FeeDistributor', label: 'FeeDistributor' },
              { type: 'doc', id: 'staking-modules/contracts/FeeOracle', label: 'FeeOracle' },
              ],
            },
            {
              type: 'category',
              label: 'Configuration',
              collapsed: false,
              items: [
              { type: 'doc', id: 'staking-modules/contracts/ParametersRegistry', label: 'ParametersRegistry' },
              { type: 'doc', id: 'staking-modules/contracts/MetaRegistry', label: 'MetaRegistry (CMv2)' },
              ],
            },
            {
              type: 'category',
              label: 'Exits and penalties',
              collapsed: false,
              items: [
              { type: 'doc', id: 'staking-modules/contracts/ValidatorStrikes', label: 'ValidatorStrikes' },
              { type: 'doc', id: 'staking-modules/contracts/ExitPenalties', label: 'ExitPenalties' },
              { type: 'doc', id: 'staking-modules/contracts/Ejector', label: 'Ejector' },
              { type: 'doc', id: 'staking-modules/contracts/Verifier', label: 'Verifier' },
              ],
            },
          ],
        },
      ],
    },
  ],
}
