module.exports = {
  docs: [
    'introduction',
    {
      type: 'doc',
      id: 'lido-v3-whitepaper',
      className: 'sidebar-v3-highlight',
    },
    'lido-dao',
    'lips',
    'guides/lido-tokens-integration-guide',
    {
      type: 'category',
      label: 'Guides',
      items: [
        {
          type: 'category',
          label: 'Curated Module',
          items: [
            'guides/curated-module/general-overview',
            'guides/curated-module/validator-keys',
            'guides/curated-module/el-rewards-configuration',
            {
              type: 'category',
              label: 'Validator Exits Automation',
              items: [
                'guides/curated-module/exits/introduction',
                'guides/curated-module/exits/general-information',
                'guides/curated-module/exits/exit-message-generation-signing',
                'guides/curated-module/exits/flow-examples',
                'guides/curated-module/exits/tooling-setup',
              ],
            },
          ],
        },
        'guides/oracle-operator-manual',
        {
          type: 'category',
          label: 'Oracle specification',
          items: [
            'guides/oracle-spec/accounting-oracle',
            'guides/oracle-spec/validator-exit-bus',
            'guides/oracle-spec/penalties',
          ],
        },
        'guides/deposit-security-manual',
        {
          type: 'category',
          label: 'Tooling',
          items: [
            'guides/tooling',
            'guides/validator-ejector-guide',
            'guides/kapi-guide',
            'guides/reward-distributor-bot',
            'guides/depositor-bot',
          ],
        },
        'guides/multisig-deployment',
        'guides/protocol-levers',
        'guides/etherscan-voting',
        'guides/dg-guide',
        'guides/easy-track-guide',
        'guides/address-ownership-guide',
        'guides/multisig-signer-manual',
        'guides/multisig-shadow-owners',
        'guides/checking-aragon-vote',
        'guides/checking-gnosis-safe',
        'guides/1inch-pool-rewards',
        'guides/early-staker-airdrop',
        'guides/jumpgates',
        'guides/verify-steth-on-optimism-upgrade-manual'
      ],
    },
    {
      type: 'category',
      label: 'Integrations',
      items: [
        'integrations/api',
        'integrations/wallets',
        'integrations/sdk',
        'integrations/subgraph',
        {
          type: 'category',
          label: 'AAVE',
          items: ['integrations/aave/specification', 'integrations/aave/aip'],
        },
      ],
    },
    {
      type: 'category',
      label: 'Token guides',
      items: [
        'token-guides/steth-superuser-functions',
        'token-guides/steth-on-aave-caveats',
        'token-guides/cross-chain-tokens-guide',
      ],
    },
    {
      type: 'category',
      label: 'Contracts',
      items: [
        'contracts/lido-locator',
        'contracts/lido',
        'contracts/eip712-steth',
        'contracts/accounting-oracle',
        'contracts/validators-exit-bus-oracle',
        'contracts/hash-consensus',
        'contracts/oracle-report-sanity-checker',
        'contracts/oracle-daemon-config',
        'contracts/staking-router',
        'contracts/vault-hub',
        'contracts/staking-vault',
        'contracts/predeposit-guarantee',
        'contracts/operator-grid',
        'contracts/lazy-oracle',
        'contracts/staking-vault-factory',
        'contracts/staking-vault-beacon',
        'contracts/dashboard',
        'contracts/validator-consolidation-requests',
        'contracts/node-operators-registry',
        'contracts/withdrawal-queue-erc721',
        'contracts/withdrawal-vault',
        'contracts/wsteth',
        'contracts/wsteth-staker',
        'contracts/deposit-security-module',
        'contracts/data-bus',
        'contracts/burner',
        'contracts/lido-execution-layer-rewards-vault',
        'contracts/mev-boost-relays-allowed-list',
        'contracts/trp-vesting-escrow',
        'contracts/gate-seal',
        'contracts/insurance',
        'contracts/ossifiable-proxy'
      ],
    },
    {
      type: 'category',
      label: 'Security',
      items: [
        'security/bugbounty',
        'security/audits',
        'security/safeharbor',
      ],
    },
    {
      type: 'category',
      label: 'Deployed contracts',
      link: { type: 'doc', id: 'deployed-contracts/index' },
      items: [
        { type: 'doc', id: 'deployed-contracts/index', label: 'Mainnet' },
        'deployed-contracts/hoodi',
        'deployed-contracts/holesky',
      ],
    },
    {
      type: 'category',
      label: 'Multisigs',
      items: [
        'multisigs/emergency-brakes',
        'multisigs/committees',
        'multisigs/alliance',
        'multisigs/other',
      ],
    },
    {
      type: 'category',
      label: 'IPFS',
      items: [
        'ipfs/about',
        'ipfs/release-flow',
        'ipfs/security',
        'ipfs/hash-verification',
        'ipfs/apps-list'
      ],
    },
    {
      type: 'category',
      label: 'Staking Modules',
      items: [
        {
          type: 'category',
          label: 'CSM',
          link: { type: 'doc', id: 'staking-modules/csm/intro' },
          items: [
            'staking-modules/csm/intro',
            'staking-modules/csm/join-csm',
            'staking-modules/csm/rewards',
            'staking-modules/csm/penalties',
            'staking-modules/csm/validator-exits',
            { type: 'doc', id: 'staking-modules/csm/permissions', label: 'Permissions' },
            {
              type: 'category',
              label: 'Contracts',
              items: [
                'staking-modules/csm/contracts/CSModule',
                'staking-modules/csm/contracts/CSAccounting',
                'staking-modules/csm/contracts/CSFeeDistributor',
                'staking-modules/csm/contracts/CSFeeOracle',
                'staking-modules/csm/contracts/CSVerifier',
                'staking-modules/csm/contracts/CSEjector',
                'staking-modules/csm/contracts/CSExitPenalties',
                'staking-modules/csm/contracts/CSParametersRegistry',
                'staking-modules/csm/contracts/CSStrikes',
                'staking-modules/csm/contracts/PermissionlessGate',
                'staking-modules/csm/contracts/VettedGate',
                'staking-modules/csm/contracts/VettedGateFactory',
              ],
            },
            'staking-modules/csm/further-reading',
          ],
        },
      ],
    },
  ],
}
